spring:
  application:
    name: spring-ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small

sfg:
  aiapp:
    vectorStorePath: G:\Git\sfg\spring-ai\src\main\resources\vectorstore\vectorstore.json
    documentsToLoad:
      - classpath:/movies500Trimmed.csv